### PR TITLE
Removed seed-isort-config repo as its deprecated

### PR DESCRIPTION
**Pull request by pkesavap**
Possible fix for : #60

### CODE REVIEW

**Comment by jugmac00** [comment]
Thanks a lot, @pkesavap!

**Comment by jugmac00** [comment]
Just a quick tip: if you write `fixes #60` or `closes #60` the issue gets automatically closed one the pull requests gets accepted.

see https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

`possible fix` is not yet on the list! It's about time!! :-)

**Comment by pkesavap** [comment]
> Just a quick tip: if you write `fixes #60` or `closes #60` the issue gets automatically closed once the pull requests gets accepted.
> 
> see https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> `possible fix` is not yet on the list! It's about time!! :-)

wow, i did not know that , thanks for the link,

**Comment by pkesavap** [comment]
@jugmac00  sorry to bother you, can you label the PR with hacktoberfest tag, its not reflecting in my profile , wonder why,

\thanks

**Comment by jugmac00** [comment]
For #hacktoberfest only pull requests between Oct 1st and Oct 31st are counted :-/

But there are many more...

https://github.com/search?q=org%3Amorepath+hacktoberfest&type=issues

**Comment by pkesavap** [comment]
> For #hacktoberfest only pull requests between Oct 1st and Oct 31st are counted :-/
> 
> But there are many more...
> 
> https://github.com/search?q=org%3Amorepath+hacktoberfest&type=issues

oh no worries , :D

**Pull request merged**
